/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteTCP;
import model.Incidente;
import model.Usuario;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Eric
 */
public class Incidentes_Usuario_Page extends javax.swing.JFrame {

    /**
     * Creates new form Listagem_Incidentes_Page
     */
    public Incidentes_Usuario_Page() {
        initComponents();
        setLocationRelativeTo(null);
        buscarIncidentesUsuario();
        this.btnRemover.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIncidentes = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        tableIncidentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_incidente", "tipo_incidente", "estado", "cidade", "bairro", "rua", "data", "hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        tableIncidentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableIncidentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableIncidentes);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnRemover))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:\

        int result = JOptionPane.showConfirmDialog(null, "Você deseja excluir este incidente ?", "Excluir Incidente",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            int linha = tableIncidentes.getSelectedRow();
            int idIncidente = Integer.parseInt(String.valueOf(tableIncidentes.getValueAt(linha, 0)));
            removerIncidente(idIncidente);
        }

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void removerIncidente(int idIncidente) {
        try {
            try {
                Usuario usuario = Usuario.getInstancia();
                int id = usuario.getId();
                String token = usuario.getToken();
                Socket socket = new Socket(ClienteTCP.getIpConexao(), ClienteTCP.getPortaConexao());
                BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                PrintWriter saida = new PrintWriter(socket.getOutputStream(), true);

                JSONObject objetoRemover = new JSONObject();
                objetoRemover.put("id_incidente", idIncidente);
                objetoRemover.put("token", token);
                objetoRemover.put("id", id);
                objetoRemover.put("operacao", 6);

                saida.println(objetoRemover.toJSONString());
                System.out.println("Enviado: " + objetoRemover.toJSONString());

                JSONParser parser = new JSONParser();
                String response = entrada.readLine();

                JSONObject jsonResponse = (JSONObject) parser.parse(response);
                System.out.println("Recebido: " + jsonResponse.toJSONString());

                if (jsonResponse.get("status").equals("OK")) {
                    JOptionPane.showMessageDialog(null, "Incidente removido com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    this.buscarIncidentesUsuario();
                }
                saida.close();
                entrada.close();
                socket.close();
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Dados recebidos com problema", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro de conexão com o servidor", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conversão do JSON", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tableIncidentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableIncidentesMouseClicked
        // TODO add your handling code here:
        this.btnRemover.setEnabled(true);
    }//GEN-LAST:event_tableIncidentesMouseClicked

    private void buscarIncidentesUsuario() {
        try {
            Usuario usuario = Usuario.getInstancia();
            int id = usuario.getId();
            String token = usuario.getToken();
            Socket socket = new Socket(ClienteTCP.getIpConexao(), ClienteTCP.getPortaConexao());
            BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            PrintWriter saida = new PrintWriter(socket.getOutputStream(), true);

            JSONObject objetoBusca = new JSONObject();
            objetoBusca.put("token", token);
            objetoBusca.put("id", id);
            objetoBusca.put("operacao", 5);

            saida.println(objetoBusca.toJSONString());
            System.out.println("Enviado: " + objetoBusca.toJSONString());

            JSONParser parser = new JSONParser();
            String response = entrada.readLine();

            JSONObject jsonResponse = (JSONObject) parser.parse(response);
            System.out.println("Recebido: " + jsonResponse.toJSONString());

            // Extrai os dados do JSON
            try {
                JSONArray incidentesJson = (JSONArray) jsonResponse.get("incidentes");
                DefaultTableModel dados = new DefaultTableModel(
                        new Object[incidentesJson.size()][8], // Número de linhas é o tamanho do array de incidentes
                        new String[]{"id_incidente", "tipo_incidente", "estado", "cidade", "bairro", "rua", "data", "hora"} // Nomes das colunas
                );

                for (int i = 0; i < incidentesJson.size(); i++) {
                    JSONObject incidenteJson = (JSONObject) incidentesJson.get(i);
                    try {
                        // incidenteJson retorna do tipo Long
                        Long tipoIncidenteLong = (Long) incidenteJson.get("tipo_incidente");
                        // após capturar tenho que fazer o parse para int
                        int tipoIncidente = tipoIncidenteLong.intValue();
                        dados.setValueAt(incidenteJson.get("id_incidente"), i, 0);
                        // envio o número que corresponde o incidente e me retorna o nome do incidente
                        dados.setValueAt(Incidente.obterTextoTipoIncidente(tipoIncidente), i, 1);
                        dados.setValueAt(incidenteJson.get("estado"), i, 2);
                        dados.setValueAt(incidenteJson.get("cidade"), i, 3);
                        dados.setValueAt(incidenteJson.get("bairro"), i, 4);
                        dados.setValueAt(incidenteJson.get("rua"), i, 5);
                        dados.setValueAt(incidenteJson.get("data"), i, 6);
                        dados.setValueAt(incidenteJson.get("hora"), i, 7);
                    } catch (NumberFormatException | ClassCastException e) {
                        JOptionPane.showMessageDialog(null, "NÃO FOI POSSÍVEL GERAR A TABELA", "Erro", JOptionPane.ERROR_MESSAGE);
                        saida.close();
                        entrada.close();
                        socket.close();
                    }

                }

                tableIncidentes.setModel(dados);
                tableIncidentes.setAutoCreateRowSorter(true);
                saida.close();
                entrada.close();
                socket.close();
            } catch (NullPointerException e) {
                saida.close();
                entrada.close();
                socket.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro de conexão com o servidor", "Erro", JOptionPane.ERROR_MESSAGE);

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conversão do JSON", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incidentes_Usuario_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incidentes_Usuario_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incidentes_Usuario_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incidentes_Usuario_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incidentes_Usuario_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableIncidentes;
    // End of variables declaration//GEN-END:variables
}
