/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;
import model.ClienteTCP;
import model.Usuario;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author a2384310
 */
public  class Perfil_Usuario_Page extends javax.swing.JFrame {
    
    private static Perfil_Usuario_Page instance;
    
    public static Perfil_Usuario_Page getInstance() {
        if (instance == null) {
            // Criar uma nova instância apenas se ainda não existir
            instance = new Perfil_Usuario_Page();
        }
        return instance;
    }
    /**
     * Creates new form Perfil_Usuario
     */
    public Perfil_Usuario_Page() {
        initComponents();
        setLocationRelativeTo(null);
        modalConfirmarSenha.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalConfirmarSenha = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditarDadosUsuario = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnRemoverConta = new javax.swing.JButton();

        modalConfirmarSenha.setMinimumSize(new java.awt.Dimension(400, 300));
        modalConfirmarSenha.setModal(true);

        jLabel1.setText("Confirme sua senha:");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modalConfirmarSenhaLayout = new javax.swing.GroupLayout(modalConfirmarSenha.getContentPane());
        modalConfirmarSenha.getContentPane().setLayout(modalConfirmarSenhaLayout);
        modalConfirmarSenhaLayout.setHorizontalGroup(
            modalConfirmarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalConfirmarSenhaLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(modalConfirmarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(modalConfirmarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(modalConfirmarSenhaLayout.createSequentialGroup()
                            .addComponent(btnConfirmar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar))
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        modalConfirmarSenhaLayout.setVerticalGroup(
            modalConfirmarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalConfirmarSenhaLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(modalConfirmarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEditarDadosUsuario.setText("EDITAR DADOS");
        btnEditarDadosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDadosUsuarioActionPerformed(evt);
            }
        });

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnRemoverConta.setText("REMOVER MINHA CONTA");
        btnRemoverConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarDadosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoverConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnEditarDadosUsuario)
                .addGap(11, 11, 11)
                .addComponent(btnRemoverConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarDadosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDadosUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Editar_Dados_Usuario_Page().setVisible(true);
    }//GEN-LAST:event_btnEditarDadosUsuarioActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inicio_Page().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRemoverContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverContaActionPerformed
        // TODO add your handling code here:
        modalConfirmarSenha.setVisible(true);
    }//GEN-LAST:event_btnRemoverContaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Você realmente deseja excluir sua conta ?", "Excluir conta",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            try {
                try {
                    String senha = Usuario.cifraDeCesar(txtSenha.getText());
                    Usuario usuario = Usuario.getInstancia();
                    int id = usuario.getId();
                    String token = usuario.getToken();
                    Socket socket = new Socket(ClienteTCP.getIpConexao(), ClienteTCP.getPortaConexao());
                    BufferedReader entrada = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                    PrintWriter saida = new PrintWriter(socket.getOutputStream(), true);

                    JSONObject objetoRemover = new JSONObject();
                    objetoRemover.put("token", token);
                    objetoRemover.put("id", id);
                    objetoRemover.put("senha", senha);
                    objetoRemover.put("operacao", 8);

                    saida.println(objetoRemover.toJSONString());
                    System.out.println("Enviado: " + objetoRemover.toJSONString());

                    JSONParser parser = new JSONParser();
                    String response = entrada.readLine();

                    JSONObject jsonResponse = (JSONObject) parser.parse(response);
                    System.out.println("Recebido: " + jsonResponse.toJSONString());

                    if (jsonResponse.get("status").equals("OK")) {
                        JOptionPane.showMessageDialog(null, "Conta removida com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                        modalConfirmarSenha.dispose();
                        this.dispose();
                        new Tipo_Usuario_Page().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, jsonResponse.get("status"), "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    }
                    saida.close();
                    entrada.close();
                    socket.close();
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Dados recebidos com problema", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro de conexão com o servidor", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Erro na conversão do JSON", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        modalConfirmarSenha.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Usuario_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Usuario_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Usuario_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Usuario_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Usuario_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEditarDadosUsuario;
    private javax.swing.JButton btnRemoverConta;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDialog modalConfirmarSenha;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
